[package]
versioned_files = [
  { path = "charts/wanderer/Chart.yaml", regex = [
    '(?m)^version:[ \t]+(?<version>[0-9]+\.[0-9]+\.[0-9]+)[ \t]*$',
    '(?m)^[ \t]+image:[ \t]+ghcr\.io/nabsku/wanderer-garmin-sync:(?<version>[0-9]+\.[0-9]+\.[0-9]+)[ \t]*$',
  ] },
  { path = "charts/wanderer/values.yaml", regex = '(?m)^[ \t]+tag:[ \t]+"(?<version>[0-9]+\.[0-9]+\.[0-9]+)"[ \t]*$' },
  { path = "README.md", regex = '(?m)^WANDERER_CHART_VERSION=(?<version>[0-9]+\.[0-9]+\.[0-9]+)[ \t]*$' },
]
changelog = "CHANGELOG.md"
scopes = ["sync", "chart", "deps"]
assets = "dist/wanderer-*.tgz"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "Release"

[[workflows]]
name = "prepare-release"

[[workflows.steps]]
type = "Command"
command = "git switch -C knope/release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = "git commit -m \"chore: prepare release $version\""

[[workflows.steps]]
type = "Command"
command = "git push --force --set-upstream origin knope/release"

[[workflows.steps]]
type = "CreatePullRequest"
base = "main"

[workflows.steps.title]
template = "chore: prepare release $version"

[workflows.steps.body]
template = "This PR was generated by Knope. Merging it will create release $version.\n\n$changelog"

[github]
owner = "Nabsku"
repo = "wanderer-helm"
